Title: Daniel Sitorus
Description: Aspiring Data Analytics/Visualisation Student with keen interest in leveraging Data to solve real-world problems. Currently sharpening my skills in visualisation and machine learning. Alywas eager to learn new techniques and collaborate on exciting projects. My Github is a collection of projects that showcases my journey. Lets connect and explore the world of Data!
theme: jekyll-theme-minimal
